#!/bin/bash

#. Continuous Integration Testing Multiplexer
#.
#. This script should be called by the CI framework; usage follows:
#.
#.     It takes 1 argument which determines in what stage of the build it has
#.     been called at.
#.
#.     It examines two environment variables:
#.
 :         ${CONTEXT?}
 :         ${MODULE?}
#.
#. See the short code below to figure out how those are used.

function run() {
    echo "$ ${@}"
    "${@}"
    return $e
}

declare -g -A PACKAGES=(
    [ALL]=make,coreutils,bash,sed,gawk,git,haveged
    [gpg,vault,remote]=gnupg2,pwgen,xclip
    [net]=iproute,net-tools,netcat,socat
    [dns,remote]=dnsutils
    [remote]=tmux,socat
)

function apt_get_install_for() {
    local module="${1}"

    local mcsv
    local buffer
    local -a pkgcsv="${PACKAGES[ALL]}"
    for mcsv in ${!PACKAGES[@]}; do
        buffer=",${mcsv},"
        if [ "${buffer/,${module},/}" != "${buffer}" ]; then
            pkgcsv+=",${PACKAGES[${mcsv}]}"
        fi
    done

    local -a packages
    IFS=, read -a packages <<< "${pkgcsv}"
    run sudo apt-get install ${packages[@]}
}

declare -g EXIT=9
echo "#. travis[$1].${CONTEXT?}(${MODULE?}) -=["
if [ $# -eq 1 ]; then
    case $1 in
        before_install)
            EXIT=0
            run sudo install -d /var/tmp -m 1777                   ;((EXIT|=$?))
            run sudo install -m 0644\
                share/unit/files/apt.conf\
                /etc/apt/apt.conf.d/99SiteUnitTest                 ;((EXIT|=$?))

            apt_get_install_for ${MODULE}                          ;((EXIT|=$?))
        ;;

        install)
            EXIT=0
            run make install                                       ;((EXIT|=$?))
        ;;

        before_script)
            EXIT=0
        ;;

        script)
            EXIT=0
            case ${CONTEXT}:${MODULE} in
                installer:-)
                    run make uninstall                             ;((EXIT|=$?)) #. Test uninstall
                    run make install                               ;((EXIT|=$?)) #. Test reinstall
                    run make purge                                 ;((EXIT|=$?)) #. Test purge
                    run make install                               ;((EXIT|=$?)) #. Test reinstall
                ;;
                execute:*)
                    run site unit test ${MODULE}                   ;((EXIT|=$?))
                ;;
                *:*)
                    EXIT=1
                ;;
            esac
        ;;

        after_success)
            EXIT=0
        ;;

        after_failure)
            EXIT=0
            run cat ~/.site/var/log/site.log
        ;;

        after_script)
            EXIT=0
            run make uninstall                                     ;((EXIT|=$?))
        ;;
    esac
fi
echo "#. ]=-"

exit $EXIT
