#!/bin/bash

#. Continuous Integration Testing Multiplexer
#.
#. This script should be called by the CI framework; usage follows:
#.
#.     It takes 1 argument which determines in what stage of the build it has
#.     been called at.
#.
#.     It examines two environment variables:
#.
 :         ${CONTEXT?}
 :         ${MODULE?}
#.
#. See the short code below to figure out how those are used.

declare -g EXIT=9
echo "#. travis[$1].${CONTEXT?}(${MODULE?}) -=["
if [ $# -eq 1 ]; then
    case $1 in
        script)
            case ${CONTEXT}:${MODULE} in
                installer:-)
                    EXIT=0
                    make install   ;((EXIT|=$?)) #. Test fresh install
                    make uninstall ;((EXIT|=$?)) #. Test uninstall
                    make install   ;((EXIT|=$?)) #. Test reinstall
                    make purge     ;((EXIT|=$?)) #. Test purge
                ;;
                execute:*)
                    EXIT=0
                    echo '$ make install'
                    make install             ;((EXIT|=$?))
                    echo "$ site unit test ${MODULE}"
                    site unit test ${MODULE} ;((EXIT|=$?))
                    echo '$ make uninstall'
                    make uninstall           ;((EXIT|=$?))
                ;;
                *:*)
                    EXIT=1
                ;;
            esac
        ;;

        before_install)
            EXIT=0
            sudo apt-get install -qq make                      ;((EXIT|=$?))
            sudo apt-get install -qq coreutils bash sed gawk   ;((EXIT|=$?))
            sudo apt-get install -qq git                       ;((EXIT|=$?))
            sudo apt-get install -qq python python-virtualenv  ;((EXIT|=$?))
            sudo install -d /var/tmp -m 1777                   ;((EXIT|=$?))
            sudo install -m 0644\
                share/unit/files/apt.conf\
                /etc/apt/apt.conf.d/99SiteUnitTest             ;((EXIT|=$?))

            case ${MODULE} in
                gpg|vault|git)
                    sudo rm -f /dev/random
                    sudo mknod -m 0666 /dev/random c 1 9 #. urandom
                    sudo install -m 0644\
                        share/unit/files/rng-tools\
                        /etc/default/rng-tools                 ;((EXIT|=$?))
                    sudo apt-get install -qq rng-tools         ;((EXIT|=$?))
                ;;
            esac

            case ${MODULE} in
                gpg|vault)
                    sudo apt-get install -qq gnupg2            ;((EXIT|=$?))
                    sudo apt-get install -qq pwgen             ;((EXIT|=$?))
                    sudo apt-get install -qq xclip             ;((EXIT|=$?))
                ;;
                net)
                    sudo apt-get install -qq iproute           ;((EXIT|=$?))
                    sudo apt-get install -qq net-tools         ;((EXIT|=$?))
                    sudo apt-get install -qq netcat            ;((EXIT|=$?))
                    sudo apt-get install -qq socat             ;((EXIT|=$?))
                ;;
            esac
        ;;
    esac
fi
echo "#. ]=-"

exit $EXIT
