#!/bin/bash

#. Continuous Integration Testing Multiplexer
#.
#. This script should be called by the CI framework; usage follows:
#.
#.     It takes 1 argument which determines in what stage of the build it has
#.     been called at.
#.
#.     It examines two environment variables:
#.
 :         ${CONTEXT?}
 :         ${MODULE?}
#.
#. See the short code below to figure out how those are used.

function run() {
    echo "$ ${@}"
    "${@}"
    return $e
}

declare -g EXIT=9
echo "#. travis[$1].${CONTEXT?}(${MODULE?}) -=["
if [ $# -eq 1 ]; then
    case $1 in
        before_install)
            EXIT=0
            run sudo apt-get install -qq make                      ;((EXIT|=$?))
            run sudo apt-get install -qq coreutils bash sed gawk   ;((EXIT|=$?))
            run sudo apt-get install -qq git                       ;((EXIT|=$?))
            run sudo apt-get install -qq haveged                   ;((EXIT|=$?))
            run sudo install -d /var/tmp -m 1777                   ;((EXIT|=$?))
            run sudo install -m 0644\
                share/unit/files/apt.conf\
                /etc/apt/apt.conf.d/99SiteUnitTest                 ;((EXIT|=$?))

            case ${MODULE} in
                gpg|vault|remote)
                    run sudo apt-get install -qq gnupg2            ;((EXIT|=$?))
                    run sudo apt-get install -qq pwgen             ;((EXIT|=$?))
                    run sudo apt-get install -qq xclip             ;((EXIT|=$?))
                ;;
            esac

            case ${MODULE} in
                net)
                    run sudo apt-get install -qq iproute           ;((EXIT|=$?))
                    run sudo apt-get install -qq net-tools         ;((EXIT|=$?))
                    run sudo apt-get install -qq netcat            ;((EXIT|=$?))
                    run sudo apt-get install -qq socat             ;((EXIT|=$?))
                ;;
            esac

            case ${MODULE} in
                dns|remote)
                    run sudo apt-get install -qq dnsutils          ;((EXIT|=$?))
                ;;
            esac

            case ${MODULE} in
                dns|remote)
                    run sudo apt-get install -qq tmux              ;((EXIT|=$?))
                ;;
            esac
        ;;

        install)
            EXIT=0
            run make install                                       ;((EXIT|=$?))
        ;;

        before_script)
            EXIT=0
        ;;

        script)
            EXIT=0
            case ${CONTEXT}:${MODULE} in
                installer:-)
                    run make uninstall                             ;((EXIT|=$?)) #. Test uninstall
                    run make install                               ;((EXIT|=$?)) #. Test reinstall
                    run make purge                                 ;((EXIT|=$?)) #. Test purge
                    run make install                               ;((EXIT|=$?)) #. Test reinstall
                ;;
                execute:*)
                    run site unit test ${MODULE}                   ;((EXIT|=$?))
                ;;
                *:*)
                    EXIT=1
                ;;
            esac
        ;;

        after_success)
            EXIT=0
        ;;

        after_failure)
            EXIT=0
            run cat ~/.site/var/log/site.log
        ;;

        after_script)
            EXIT=0
            run make uninstall                                     ;((EXIT|=$?))
        ;;
    esac
fi
echo "#. ]=-"

exit $EXIT
