#!/usr/bin/python

import os, sys
def vault(sid):
    secrets = '%s/.secrets' % os.environ['HOME']
    if os.path.exists(secrets):
        from io import BytesIO
        o = BytesIO()
        with open(secrets, 'r') as ifH:
            from gpgme import Context
            ctx = Context()
            ctx.armor = True
            ctx.decrypt(ifH, o)
        return dict(
            (_.split(None, 1) for _ in o.getvalue().split('\n') if _)
        ).get(sid, '').strip()

if __name__ == '__main__':
    e = 0
    if len(sys.argv) == 2:
        s = vault(sys.argv[1])
        if s:
            if sys.stdout.isatty():
                from subprocess import Popen, PIPE
                p = Popen(['xsel','-si'], stdin=PIPE)
                p.communicate(input=s)
            else:
                print(s)
        else:
            e = 1
    else:
        print("Usage: %s <secret-id>" % os.path.basename(sys.argv[0]))

    exit(e)
